### ISSUE TITLE
PlayerVaults cloning and not saving to UUID when accessing someone else's vault - loading old / wrong contents.

### ISSUE THREAD

**Issue by mibby** [drtshock/PlayerVaults#215]
@drtshock 

PlayerVaults dev 205
PaperSpigot dev 832

Got a bug to report. An admin of mine is able to access his pv just fine -  /pv 1-3. But when someone else accesses their vault with `/pv <name> 1`, it is different. It is still their PV but from a different time (the date it was originally first tried to be viewed). And accessing with different capitalization `/pv naME 1` is again still that person's PV but cloned under a different capitalization and different time it was snapshotted.  When accessing their 2nd pv with yet again a different capitalization, it was not their PV but the admin's who was viewing it.

It is as if using admin access to look into other's chests is not actually reading from the UUID, but rather cloning the contents into a named yml. As well as sometimes cloning your PV as theirs by mistake.

![link](http://i.imgur.com/Aeh1Wrc.png)

**Comment by Menfie** [comment]
I also can confirm these bugs. Admin's just cannot edit player's vault's because when you take out an item out of player's vault its still there! It's only gone if actual player take it out. Also you should add an protection for it like when someone editing a vault any other person shouldn't be able to edit it or open it. Because from what I see this causes alot of issues. I hope you fix these issues soon...

**Comment by DataStoreRBLX** [comment]
Can also confirm that this is happening - And also had issues before, whereby if an admin edited at the same time as a the user, the items were duplicated; with the user quizzing us as to why we hadn't taken X, Y or Z token from them when we had.

Hopefully this is fixed soon, as it's a complete pain - Especially when we're trying to confiscate items from a user.

**Comment by mibby** [comment]
@drtshock @kashike Bump. Any update to this problem? :(

**Comment by mibby** [comment]
@kashike @Byteflux This is still a problem as of this commit https://github.com/drtshock/PlayerVaults/commit/25120bef1aba6e6f3de291b05e3d0a75c61df9ea (dev 208). Meaning you still can not look into someone else's vault. It loads a snapshot of the contents from when you first tried to view the vault and is saved based on their displayname / the exact way you typed the name in the command. It doesn't view (or save) the vault based on the player's UUID.

i.e. 

```/pv mibby 1``` and ```/pv Mibby 1``` are both derived from my original chest but from different snapshots since the contents are saved in mibby.yml and Mibby.yml.

**Comment by Byteflux** [comment]
I have no problem looking into others' vaults. Tagging me probably isn't appropriate, though. I'm not a PlayerVaults developer, and that commit is intended to fix a different issue.

**Comment by mibby** [comment]
My apologies. I was not sure if you were committing fixes with others to knock some of the more atrocious bugs out of the plugin. This issue is reproducible 100% of the time, so I can only assume you are not using UUIDs or must not understand the issue fully.

**Comment by Braleth** [comment]
Confirming this is still an issue under dev build 209, running on Spigot 1.11.2 (version git-Spigot-4741400-a1d3777).

The only time you can see the real version of a player's vault is to manually delete the named cached copy (playername.yml) that is created. Other wise, all admins see the cached copy from that point forward.
